// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpbfsrqnybukbgxcnjzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwYmZzcnFueWJ1a2JneGNuanprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTgzMTgsImV4cCI6MjA2OTg5NDMxOH0.8yUY4Ews4-yWrSrHJL8xdj-uKySz1rCaT255BKMzL8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Set session timeout to 2 hours (7200 seconds)
    sessionRefreshInterval: 300, // Refresh session every 5 minutes
    // Detect when tab becomes visible to check session
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'mangal-admin-app',
    },
  },
});
